# Generated by Django 3.0.5 on 2020-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
