# Generated by Django 3.0.5 on 2020-04-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_auto_20200409_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, through='music_app.Membership', to='music_app.Musician'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.Musician'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
