# Generated by Django 3.0.5 on 2020-04-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_auto_20200409_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BandMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('position', models.CharField(max_length=64)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.Band')),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.Musician')),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(through='music_app.BandMembership', to='music_app.Musician'),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.Band'),
        ),
    ]
